generation_config:
  missing_environment: ignore
environments:
  native:
    env_vars:
      NATIVE: true
      BUILD_MVN_OPTS_CURRENT: -Dnative -Dquarkus.native.container-build=true
      ADDITIONAL_TIMEOUT: 720
    ids:
    - native
  sonarcloud:
    auto_generation: false
    env_vars:
      ENABLE_SONARCLOUD: true
    ids:
    - sonarcloud
    - coverage
  ecosystem:
    auto_generation: false
    ids:
    - ecosystem
disable:
  images-deploy: false
repositories:
- name: incubator-kie-kogito-pipelines
  job_display_name: kogito-pipelines
- name: incubator-kie-kogito-runtimes
  job_display_name: kogito-runtimes
- name: incubator-kie-kogito-apps
  job_display_name: kogito-apps
- name: incubator-kie-kogito-images
  job_display_name: kogito-images
git:
  author:
    name: test-kie-pipelines
    # Taken from https://ci-builds.apache.org/credentials/
    # Need to be verified
    credentials_id: test-kie-pipelines
    token_credentials_id: test-kie-pipelines-token
    push:
      credentials_id: test-kie-pipelines-push # CI Push Access for KIE
      token_credentials_id: test-kie-pipelines-push-token # GitHub Personal Access Token for KIE
  fork_author:
    name: kie-ci
    credentials_id: kie-ci
    push:
      credentials_id: kie-ci
  quarkus:
    author:
      name: quarkusio
      credentials_id: kie-ci
    branch: main
  jenkins_config_path: .ci/jenkins
buildchain_config:
  git:
    repository: incubator-kie-kogito-pipelines
    file_path: .ci/pull-request-config.yaml
    token_credentials_id: test-kie-pipelines-token
maven:
  settings_file_id: kie-release-settings
  nexus:
    release_url: TO_DEFINE
    release_repository: TO_DEFINE
    staging_profile_url: TO_DEFINE
    staging_profile_id: TO_DEFINE
    build_promotion_profile_id: TO_DEFINE
  artifacts_repository: ''
  artifacts_upload_repository:
    url: https://repository.apache.org/content/repositories/snapshots
    creds_id: apache-nexus-kie-deploy-credentials
  quarkus_platform_repository:
    url: TO_DEFINE
    creds_id: TO_DEFINE
cloud:
  image:
    registry_user_credentials_id: DOCKERHUB_USER
    registry_token_credentials_id: DOCKERHUB_TOKEN
    registry: docker.io
    namespace: apache
    latest_git_branch: main
release:
  gpg:
    sign:
      key-credentials-id: 'asf-release-gpg-signing-key'
      passphrase-credentials-id: 'asf-release-gpg-signing-key-passphrase'
  svn:
    staging-repository: <TO-BE-DEFINED>
    credentials-id: <TO-BE-DEFINED>
jenkins:
  email_creds_id: KOGITO_CI_NOTIFICATION_EMAILS
  agent:
    docker:
      builder:
        # At some point, this image will need to be changed when a release branch is created 
        # but we need to make sure the image exists first ... simple tag before setting up the branch ?
        # See https://github.com/kiegroup/kie-issues/issues/551
        image: docker.io/apache/incubator-kie-kogito-ci-build:main-latest
        args: --privileged --group-add docker
  default_tools:
    jdk: jdk_17_latest
    maven: maven_3.9.3
    sonar_jdk: jdk_17_latest
  jobs_definition_file: .ci/jenkins/dsl/jobs.groovy
